import type { Metadata } from "next";
import { MedievalSharp } from "next/font/google";
import "./globals.css";

const medievalSharp = MedievalSharp({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
  variable: "--medievalSharp", // Define the font variable
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={medievalSharp.variable}>
      <body className="antialiased">{children}</body>
    </html>
  );
}