import type { Metadata } from "next";
import { Almendra_SC, IM_Fell_English, MedievalSharp, Wix_Madefor_Display } from "next/font/google";
import "./globals.css";
import Providers from "./components/Provider";

const defaultfont = Wix_Madefor_Display({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
  variable: "--default-font", // Define the font variable
});

const medievalfont = MedievalSharp({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
  variable: "--medieval-font", // Define the font variable
});

const alemendra = Almendra_SC({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
  variable: "--alemendra-font", // Define the font variable
});

const imefellenglish = IM_Fell_English({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
  variable: "--imfellenglish-font", // Define the font variable
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${defaultfont.variable} ${medievalfont.variable} ${alemendra.variable} ${imefellenglish.variable}`}>
      <body className="antialiased">
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}